//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvc_entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_jogador
    {
        public int id_jogador { get; set; }
        public int time_jogador { get; set; }
        public string nome_jogador { get; set; }
    
        public virtual tb_times tb_times { get; set; }
    }
}
